
// includes from the plugin
// [[Rcpp::plugins(cpp14)]]


// user includes
#include <Rcpp.h>
using namespace Rcpp;
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
#ifndef USE_STANC3
#define USE_STANC3
#endif
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace modelf24ec4616b9_ucip_bayes_HalfNormal_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 21> locations_array__ =
  {" (found before start of program)",
  " (in 'ucip_bayes_HalfNormal', line 10, column 2 to column 10)",
  " (in 'ucip_bayes_HalfNormal', line 11, column 2 to column 20)",
  " (in 'ucip_bayes_HalfNormal', line 12, column 2 to column 14)",
  " (in 'ucip_bayes_HalfNormal', line 15, column 2 to column 18)",
  " (in 'ucip_bayes_HalfNormal', line 16, column 2 to column 23)",
  " (in 'ucip_bayes_HalfNormal', line 19, column 2 to column 36)",
  " (in 'ucip_bayes_HalfNormal', line 20, column 2 to column 32)",
  " (in 'ucip_bayes_HalfNormal', line 21, column 2 to column 19)",
  " (in 'ucip_bayes_HalfNormal', line 23, column 4 to column 52)",
  " (in 'ucip_bayes_HalfNormal', line 22, column 2 to line 23, column 52)",
  " (in 'ucip_bayes_HalfNormal', line 2, column 2 to column 17)",
  " (in 'ucip_bayes_HalfNormal', line 3, column 9 to column 10)",
  " (in 'ucip_bayes_HalfNormal', line 3, column 2 to column 22)",
  " (in 'ucip_bayes_HalfNormal', line 4, column 18 to column 19)",
  " (in 'ucip_bayes_HalfNormal', line 4, column 2 to column 23)",
  " (in 'ucip_bayes_HalfNormal', line 5, column 2 to column 18)",
  " (in 'ucip_bayes_HalfNormal', line 6, column 2 to column 25)",
  " (in 'ucip_bayes_HalfNormal', line 7, column 2 to column 29)",
  " (in 'ucip_bayes_HalfNormal', line 12, column 9 to column 10)",
  " (in 'ucip_bayes_HalfNormal', line 15, column 9 to column 10)"};
class modelf24ec4616b9_ucip_bayes_HalfNormal final : public model_base_crtp<modelf24ec4616b9_ucip_bayes_HalfNormal> {
private:
  int N;
  Eigen::Matrix<double,-1,1> theta_hat_data__;
  Eigen::Matrix<double,-1,1> V_data__;
  double prior_mean;
  double prior_sd;
  double prior_tau_sd;
  Eigen::Map<Eigen::Matrix<double,-1,1>> theta_hat{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> V{nullptr, 0};
public:
  ~modelf24ec4616b9_ucip_bayes_HalfNormal() {}
  modelf24ec4616b9_ucip_bayes_HalfNormal(stan::io::var_context& context__,
                                         unsigned int random_seed__ = 0,
                                         std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "modelf24ec4616b9_ucip_bayes_HalfNormal_namespace::modelf24ec4616b9_ucip_bayes_HalfNormal";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 11;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 11;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 12;
      stan::math::validate_non_negative_index("theta_hat", "N", N);
      current_statement__ = 13;
      context__.validate_dims("data initialization", "theta_hat", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      theta_hat_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                           std::numeric_limits<double>::quiet_NaN());
      new (&theta_hat)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(theta_hat_data__.data(), N);
      {
        std::vector<local_scalar_t__> theta_hat_flat__;
        current_statement__ = 13;
        theta_hat_flat__ = context__.vals_r("theta_hat");
        current_statement__ = 13;
        pos__ = 1;
        current_statement__ = 13;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 13;
          stan::model::assign(theta_hat, theta_hat_flat__[(pos__ - 1)],
            "assigning variable theta_hat", stan::model::index_uni(sym1__));
          current_statement__ = 13;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 14;
      stan::math::validate_non_negative_index("V", "N", N);
      current_statement__ = 15;
      context__.validate_dims("data initialization", "V", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      V_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&V) Eigen::Map<Eigen::Matrix<double,-1,1>>(V_data__.data(), N);
      {
        std::vector<local_scalar_t__> V_flat__;
        current_statement__ = 15;
        V_flat__ = context__.vals_r("V");
        current_statement__ = 15;
        pos__ = 1;
        current_statement__ = 15;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 15;
          stan::model::assign(V, V_flat__[(pos__ - 1)],
            "assigning variable V", stan::model::index_uni(sym1__));
          current_statement__ = 15;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "V", V, 0);
      current_statement__ = 16;
      context__.validate_dims("data initialization", "prior_mean", "double",
        std::vector<size_t>{});
      prior_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 16;
      prior_mean = context__.vals_r("prior_mean")[(1 - 1)];
      current_statement__ = 17;
      context__.validate_dims("data initialization", "prior_sd", "double",
        std::vector<size_t>{});
      prior_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 17;
      prior_sd = context__.vals_r("prior_sd")[(1 - 1)];
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "prior_sd", prior_sd, 0);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "prior_tau_sd",
        "double", std::vector<size_t>{});
      prior_tau_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 18;
      prior_tau_sd = context__.vals_r("prior_tau_sd")[(1 - 1)];
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "prior_tau_sd",
        prior_tau_sd, 0);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("z", "N", N);
      current_statement__ = 20;
      stan::math::validate_non_negative_index("theta", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + N;
  }
  inline std::string model_name() const final {
    return "modelf24ec4616b9_ucip_bayes_HalfNormal";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "modelf24ec4616b9_ucip_bayes_HalfNormal_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.template read<local_scalar_t__>();
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 2;
      tau = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 3;
      z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(theta,
        stan::math::add(mu, stan::math::multiply(tau, z)),
        "assigning variable theta");
      {
        current_statement__ = 6;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, prior_mean,
                         prior_sd));
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(tau, 0, prior_tau_sd));
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(z, 0, 1));
        current_statement__ = 10;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 9;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(theta_hat, "theta_hat",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(theta, "theta",
                             stan::model::index_uni(i)), (1 /
                           stan::math::sqrt(
                             stan::model::rvalue(V, "V",
                               stan::model::index_uni(i))))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "modelf24ec4616b9_ucip_bayes_HalfNormal_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      mu = in__.template read<local_scalar_t__>();
      double tau = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      tau = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double,-1,1> z =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      Eigen::Matrix<double,-1,1> theta =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(mu);
      out__.write(tau);
      out__.write(z);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 5;
      stan::model::assign(theta,
        stan::math::add(mu, stan::math::multiply(tau, z)),
        "assigning variable theta");
      if (emit_transformed_parameters__) {
        out__.write(theta);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.read<local_scalar_t__>();
      out__.write(mu);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 2;
      tau = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, tau);
      Eigen::Matrix<local_scalar_t__,-1,1> z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(z,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N),
        "assigning variable z");
      out__.write(z);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "tau", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "z", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = context__.vals_r("mu")[(1 - 1)];
      out__.write(mu);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 2;
      tau = context__.vals_r("tau")[(1 - 1)];
      out__.write_free_lb(0, tau);
      Eigen::Matrix<local_scalar_t__,-1,1> z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_flat__;
        current_statement__ = 3;
        z_flat__ = context__.vals_r("z");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(z, z_flat__[(pos__ - 1)],
            "assigning variable z", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu", "tau", "z"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"theta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(N)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "z" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "z" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + N);
    const size_t num_transformed = emit_transformed_parameters * (N);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + N);
    const size_t num_transformed = emit_transformed_parameters * (N);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = modelf24ec4616b9_ucip_bayes_HalfNormal_namespace::modelf24ec4616b9_ucip_bayes_HalfNormal;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return modelf24ec4616b9_ucip_bayes_HalfNormal_namespace::profiles__;
}
#endif
#endif

RCPP_MODULE(stan_fit4modelf24ec4616b9_ucip_bayes_HalfNormal_mod) {
  class_<rstan::stan_fit<stan_model, boost::random::ecuyer1988> >(
      "stan_fit4modelf24ec4616b9_ucip_bayes_HalfNormal")

      .constructor<SEXP, SEXP, SEXP>()

      .method(
          "call_sampler",
          &rstan::stan_fit<stan_model, boost::random::ecuyer1988>::call_sampler)
      .method(
          "param_names",
          &rstan::stan_fit<stan_model, boost::random::ecuyer1988>::param_names)
      .method("param_names_oi",
              &rstan::stan_fit<stan_model,
                               boost::random::ecuyer1988>::param_names_oi)
      .method("param_fnames_oi",
              &rstan::stan_fit<stan_model,
                               boost::random::ecuyer1988>::param_fnames_oi)
      .method(
          "param_dims",
          &rstan::stan_fit<stan_model, boost::random::ecuyer1988>::param_dims)
      .method("param_dims_oi",
              &rstan::stan_fit<stan_model,
                               boost::random::ecuyer1988>::param_dims_oi)
      .method("update_param_oi",
              &rstan::stan_fit<stan_model,
                               boost::random::ecuyer1988>::update_param_oi)
      .method("param_oi_tidx",
              &rstan::stan_fit<stan_model,
                               boost::random::ecuyer1988>::param_oi_tidx)
      .method("grad_log_prob",
              &rstan::stan_fit<stan_model,
                               boost::random::ecuyer1988>::grad_log_prob)
      .method("log_prob",
              &rstan::stan_fit<stan_model, boost::random::ecuyer1988>::log_prob)
      .method("unconstrain_pars",
              &rstan::stan_fit<stan_model,
                               boost::random::ecuyer1988>::unconstrain_pars)
      .method("constrain_pars",
              &rstan::stan_fit<stan_model,
                               boost::random::ecuyer1988>::constrain_pars)
      .method(
          "num_pars_unconstrained",
          &rstan::stan_fit<stan_model,
                           boost::random::ecuyer1988>::num_pars_unconstrained)
      .method(
          "unconstrained_param_names",
          &rstan::stan_fit<
              stan_model, boost::random::ecuyer1988>::unconstrained_param_names)
      .method(
          "constrained_param_names",
          &rstan::stan_fit<stan_model,
                           boost::random::ecuyer1988>::constrained_param_names)
      .method("standalone_gqs",
              &rstan::stan_fit<stan_model,
                               boost::random::ecuyer1988>::standalone_gqs);
}


// declarations
extern "C" {
SEXP filef24ec22c688be( ) ;
}

// definition
SEXP filef24ec22c688be() {
 return Rcpp::wrap("ucip_bayes_HalfNormal");
}

